// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/pb/grpctask.proto

package grpctask

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=LastName,proto3" json:"LastName,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=Email,proto3" json:"Email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_860d8d2710c75e9e, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type Request struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_860d8d2710c75e9e, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Response struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=Users,proto3" json:"Users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_860d8d2710c75e9e, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "grpctask.User")
	proto.RegisterType((*Request)(nil), "grpctask.Request")
	proto.RegisterType((*Response)(nil), "grpctask.Response")
}

func init() { proto.RegisterFile("api/pb/grpctask.proto", fileDescriptor_860d8d2710c75e9e) }

var fileDescriptor_860d8d2710c75e9e = []byte{
	// 257 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x6f, 0x4a, 0x03, 0x31,
	0x10, 0xc5, 0xd9, 0x3f, 0xad, 0xbb, 0x53, 0x58, 0x70, 0x50, 0x58, 0x96, 0x0a, 0xcb, 0xe2, 0x87,
	0xfd, 0xd4, 0x95, 0x7a, 0x03, 0x41, 0xa1, 0x50, 0x04, 0x23, 0x1e, 0x20, 0x6d, 0xe3, 0x12, 0x6c,
	0x93, 0x98, 0x49, 0x3d, 0x80, 0x57, 0xf0, 0x68, 0x5e, 0xc1, 0x83, 0x48, 0xb2, 0xb5, 0xf5, 0xdb,
	0xbc, 0xf7, 0x9b, 0xc7, 0x4b, 0x06, 0x2e, 0xb9, 0x91, 0x9d, 0x59, 0x75, 0xbd, 0x35, 0x6b, 0xc7,
	0xe9, 0x6d, 0x66, 0xac, 0x76, 0x1a, 0xb3, 0x3f, 0x5d, 0x4d, 0x7b, 0xad, 0xfb, 0xad, 0xe8, 0xfc,
	0x1e, 0x57, 0x4a, 0x3b, 0xee, 0xa4, 0x56, 0x34, 0xec, 0x35, 0xaf, 0x90, 0xbe, 0x90, 0xb0, 0x58,
	0x40, 0xbc, 0xd8, 0x94, 0x51, 0x1d, 0xb5, 0x09, 0x8b, 0x17, 0x1b, 0x9c, 0x42, 0xfe, 0x20, 0x2d,
	0xb9, 0x47, 0xbe, 0x13, 0x65, 0x5c, 0x47, 0x6d, 0xce, 0x4e, 0x06, 0x56, 0x90, 0x2d, 0xf9, 0x01,
	0x26, 0x01, 0x1e, 0x35, 0x5e, 0xc0, 0xe8, 0x7e, 0xc7, 0xe5, 0xb6, 0x4c, 0x03, 0x18, 0x44, 0x73,
	0x05, 0x67, 0x4c, 0xbc, 0xef, 0x05, 0x39, 0x44, 0x48, 0x95, 0x0f, 0x46, 0x81, 0x87, 0xb9, 0xb9,
	0x81, 0x8c, 0x09, 0x32, 0x5a, 0x91, 0xc0, 0x6b, 0x18, 0xf9, 0x27, 0x51, 0x19, 0xd5, 0x49, 0x3b,
	0x99, 0x17, 0xb3, 0xe3, 0xd7, 0xbc, 0xcd, 0x06, 0x38, 0x7f, 0x82, 0x89, 0x1f, 0x9e, 0x85, 0xfd,
	0x90, 0x6b, 0x81, 0x77, 0x90, 0x2f, 0x25, 0xb9, 0xc0, 0xf0, 0xfc, 0x14, 0x39, 0x94, 0x56, 0xf8,
	0xdf, 0x1a, 0x8a, 0x9a, 0xe2, 0xf3, 0xfb, 0xe7, 0x2b, 0xce, 0x70, 0xdc, 0xed, 0x7d, 0x6c, 0x35,
	0x0e, 0x27, 0xb9, 0xfd, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x6a, 0x38, 0xcc, 0x0c, 0x53, 0x01, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	ListUsers(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) ListUsers(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/grpctask.UserService/ListUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	ListUsers(context.Context, *Request) (*Response, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) ListUsers(ctx context.Context, req *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUsers not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpctask.UserService/ListUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ListUsers(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpctask.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListUsers",
			Handler:    _UserService_ListUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/pb/grpctask.proto",
}
