// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/grpctask.proto

package grpctask

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=LastName,proto3" json:"LastName,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=Email,proto3" json:"Email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f4e05a9a5a53bfd, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type Message struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	UserId               int64    `protobuf:"varint,3,opt,name=UserId,proto3" json:"UserId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f4e05a9a5a53bfd, []int{1}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Message) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Message) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f4e05a9a5a53bfd, []int{2}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

type UserResponse struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=Users,proto3" json:"Users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f4e05a9a5a53bfd, []int{3}
}

func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (m *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(m, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type UserRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRequest) Reset()         { *m = UserRequest{} }
func (m *UserRequest) String() string { return proto.CompactTextString(m) }
func (*UserRequest) ProtoMessage()    {}
func (*UserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f4e05a9a5a53bfd, []int{4}
}

func (m *UserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRequest.Unmarshal(m, b)
}
func (m *UserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRequest.Marshal(b, m, deterministic)
}
func (m *UserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRequest.Merge(m, src)
}
func (m *UserRequest) XXX_Size() int {
	return xxx_messageInfo_UserRequest.Size(m)
}
func (m *UserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRequest proto.InternalMessageInfo

func (m *UserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type MessageResponse struct {
	Messages             []*Message `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *MessageResponse) Reset()         { *m = MessageResponse{} }
func (m *MessageResponse) String() string { return proto.CompactTextString(m) }
func (*MessageResponse) ProtoMessage()    {}
func (*MessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f4e05a9a5a53bfd, []int{5}
}

func (m *MessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageResponse.Unmarshal(m, b)
}
func (m *MessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageResponse.Marshal(b, m, deterministic)
}
func (m *MessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageResponse.Merge(m, src)
}
func (m *MessageResponse) XXX_Size() int {
	return xxx_messageInfo_MessageResponse.Size(m)
}
func (m *MessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MessageResponse proto.InternalMessageInfo

func (m *MessageResponse) GetMessages() []*Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

type MessageRequest struct {
	Message              *Message `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageRequest) Reset()         { *m = MessageRequest{} }
func (m *MessageRequest) String() string { return proto.CompactTextString(m) }
func (*MessageRequest) ProtoMessage()    {}
func (*MessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f4e05a9a5a53bfd, []int{6}
}

func (m *MessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageRequest.Unmarshal(m, b)
}
func (m *MessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageRequest.Marshal(b, m, deterministic)
}
func (m *MessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageRequest.Merge(m, src)
}
func (m *MessageRequest) XXX_Size() int {
	return xxx_messageInfo_MessageRequest.Size(m)
}
func (m *MessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MessageRequest proto.InternalMessageInfo

func (m *MessageRequest) GetMessage() *Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "grpctask.User")
	proto.RegisterType((*Message)(nil), "grpctask.Message")
	proto.RegisterType((*Request)(nil), "grpctask.Request")
	proto.RegisterType((*UserResponse)(nil), "grpctask.UserResponse")
	proto.RegisterType((*UserRequest)(nil), "grpctask.UserRequest")
	proto.RegisterType((*MessageResponse)(nil), "grpctask.MessageResponse")
	proto.RegisterType((*MessageRequest)(nil), "grpctask.MessageRequest")
}

func init() { proto.RegisterFile("pb/grpctask.proto", fileDescriptor_0f4e05a9a5a53bfd) }

var fileDescriptor_0f4e05a9a5a53bfd = []byte{
	// 561 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x55, 0x3e, 0x9a, 0x8f, 0x31, 0x0d, 0x64, 0x04, 0x95, 0x31, 0x15, 0x8a, 0x56, 0x1c, 0xa2,
	0x54, 0xb5, 0xd5, 0x02, 0x12, 0x8a, 0x04, 0x42, 0xd0, 0xa6, 0x8a, 0xda, 0xf4, 0x10, 0xe8, 0x0f,
	0x70, 0xea, 0xad, 0x65, 0x35, 0xb1, 0x5d, 0xef, 0x06, 0xa9, 0x82, 0x5e, 0xf8, 0x0b, 0xfc, 0x34,
	0x8e, 0x5c, 0xf9, 0x21, 0xc8, 0xb3, 0x6b, 0x07, 0xe2, 0x46, 0x55, 0xca, 0xc9, 0x9a, 0x7d, 0x33,
	0xef, 0xbd, 0xd9, 0x7d, 0x86, 0x76, 0x3c, 0x71, 0xfc, 0x24, 0x3e, 0x97, 0xae, 0xb8, 0xb4, 0xe3,
	0x24, 0x92, 0x11, 0x36, 0xb2, 0xda, 0xda, 0xf6, 0xa3, 0xc8, 0x9f, 0x72, 0xc7, 0x8d, 0x03, 0xc7,
	0x0d, 0xc3, 0x48, 0xba, 0x32, 0x88, 0x42, 0xa1, 0xfa, 0xac, 0x67, 0x1a, 0xa5, 0x6a, 0x32, 0xbf,
	0x70, 0xf8, 0x2c, 0x96, 0xd7, 0x0a, 0x64, 0x17, 0x50, 0x3d, 0x13, 0x3c, 0xc1, 0x16, 0x94, 0x87,
	0x9e, 0x59, 0xea, 0x94, 0xba, 0x95, 0x71, 0x79, 0xe8, 0xe1, 0x36, 0x34, 0x07, 0x41, 0x22, 0xe4,
	0xa9, 0x3b, 0xe3, 0x66, 0xb9, 0x53, 0xea, 0x36, 0xc7, 0x8b, 0x03, 0xb4, 0xa0, 0x71, 0xe2, 0x6a,
	0xb0, 0x42, 0x60, 0x5e, 0xe3, 0x63, 0xd8, 0x38, 0x9c, 0xb9, 0xc1, 0xd4, 0xac, 0x12, 0xa0, 0x0a,
	0x76, 0x0c, 0xf5, 0x11, 0x17, 0xc2, 0xf5, 0x79, 0x41, 0xca, 0xcc, 0x21, 0x2d, 0x94, 0x77, 0x6e,
	0x41, 0x2d, 0x35, 0x37, 0xf4, 0x48, 0xa4, 0x32, 0xd6, 0x15, 0x6b, 0x42, 0x7d, 0xcc, 0xaf, 0xe6,
	0x5c, 0x48, 0xf6, 0x0a, 0x1e, 0xa4, 0x87, 0x63, 0x2e, 0xe2, 0x28, 0x14, 0x1c, 0x5f, 0xc0, 0x46,
	0x5a, 0x0b, 0xb3, 0xd4, 0xa9, 0x74, 0x8d, 0xfd, 0x96, 0x9d, 0x5f, 0x1a, 0xb5, 0x29, 0x90, 0xed,
	0x81, 0xa1, 0xa6, 0x88, 0x04, 0x19, 0x54, 0xe7, 0x82, 0x27, 0xe4, 0xa9, 0x38, 0x43, 0x18, 0x7b,
	0x0f, 0x0f, 0xb5, 0xad, 0x5c, 0x6b, 0x17, 0x1a, 0x33, 0x75, 0x94, 0xc9, 0xb5, 0x17, 0xa3, 0x59,
	0x73, 0xde, 0xc2, 0xde, 0x42, 0x2b, 0x67, 0x50, 0xba, 0x3b, 0x50, 0xd7, 0xa8, 0x96, 0xbe, 0x65,
	0x3e, 0xeb, 0xd8, 0xff, 0x55, 0x57, 0xa6, 0x3f, 0xf1, 0xe4, 0x4b, 0x70, 0xce, 0x71, 0x00, 0xcd,
	0x93, 0x40, 0x48, 0x5a, 0x08, 0xff, 0x1a, 0xd4, 0xe4, 0xd6, 0xd6, 0xd2, 0x1a, 0xda, 0x35, 0x6b,
	0x7d, 0xff, 0xf9, 0xfb, 0x47, 0xb9, 0x81, 0x35, 0x67, 0x4e, 0xa3, 0x47, 0x00, 0x1f, 0x13, 0xee,
	0x4a, 0xae, 0x72, 0xf0, 0xef, 0x54, 0xca, 0x42, 0xe9, 0xb1, 0xb3, 0xf4, 0xd8, 0x87, 0x69, 0x7a,
	0x58, 0x9b, 0x58, 0x0c, 0xa6, 0x59, 0xfa, 0xa5, 0x1e, 0x7e, 0x06, 0xe3, 0x2c, 0xf6, 0x5c, 0xc9,
	0xbd, 0x0f, 0xd7, 0xc3, 0x03, 0x7c, 0xb2, 0xac, 0xaf, 0x6c, 0x2d, 0x09, 0xb0, 0xe7, 0x44, 0x64,
	0x5a, 0x8f, 0x14, 0x91, 0xf3, 0x35, 0xfd, 0xd8, 0x43, 0xef, 0xa6, 0x4f, 0xf7, 0x8e, 0xa7, 0x60,
	0x1c, 0xf0, 0x29, 0x5f, 0x93, 0xd5, 0x24, 0x56, 0xec, 0x15, 0x58, 0xf1, 0x18, 0x1a, 0x83, 0x20,
	0xbc, 0x0f, 0x19, 0x16, 0xc9, 0x2e, 0x01, 0x8e, 0x38, 0x3d, 0xc1, 0x48, 0xf8, 0x68, 0x16, 0x5f,
	0x4f, 0x33, 0x3e, 0xbd, 0x05, 0xd1, 0xcf, 0xd1, 0x25, 0x72, 0x86, 0x9d, 0x8c, 0x5c, 0xbf, 0xb7,
	0xad, 0xb2, 0x7e, 0xe3, 0x64, 0xf9, 0xc1, 0x2b, 0x30, 0x52, 0xe7, 0x23, 0xe1, 0x93, 0xf9, 0xd5,
	0x6a, 0xc5, 0x14, 0xb1, 0xd7, 0xa4, 0xe2, 0xe0, 0xee, 0x5d, 0x2a, 0x0b, 0x24, 0xdd, 0x4f, 0xc2,
	0xa6, 0xca, 0x46, 0xf6, 0x47, 0xae, 0x16, 0x5d, 0x15, 0x94, 0x3d, 0x52, 0xde, 0x61, 0x77, 0xee,
	0xd7, 0xcf, 0x92, 0x8e, 0xdf, 0x60, 0x53, 0x05, 0xe9, 0x5e, 0xab, 0xbe, 0x23, 0xc1, 0x37, 0xd6,
	0x7a, 0xab, 0x2e, 0xd4, 0x25, 0xb4, 0x74, 0xe0, 0xfe, 0xe7, 0xa6, 0x7b, 0xeb, 0xc9, 0x4f, 0x6a,
	0x74, 0x6d, 0x2f, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0xba, 0xfa, 0xe7, 0xce, 0xe8, 0x05, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	ListUsers(ctx context.Context, in *Request, opts ...grpc.CallOption) (*UserResponse, error)
	CreateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*empty.Empty, error)
	UpdatedByID(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*User, error)
	DeletedByID(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*User, error)
	FindByID(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*User, error)
	GetUserMsg(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*MessageResponse, error)
	FindMsgByID(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*Message, error)
	CreateMessage(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	UpdateMsgByID(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*Message, error)
	DeletedMsgByID(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*Message, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) ListUsers(ctx context.Context, in *Request, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/grpctask.UserService/ListUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CreateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/grpctask.UserService/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdatedByID(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/grpctask.UserService/UpdatedByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DeletedByID(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/grpctask.UserService/DeletedByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) FindByID(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/grpctask.UserService/FindByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUserMsg(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*MessageResponse, error) {
	out := new(MessageResponse)
	err := c.cc.Invoke(ctx, "/grpctask.UserService/GetUserMsg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) FindMsgByID(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/grpctask.UserService/FindMsgByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CreateMessage(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/grpctask.UserService/CreateMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateMsgByID(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/grpctask.UserService/UpdateMsgByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DeletedMsgByID(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/grpctask.UserService/DeletedMsgByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	ListUsers(context.Context, *Request) (*UserResponse, error)
	CreateUser(context.Context, *User) (*empty.Empty, error)
	UpdatedByID(context.Context, *UserRequest) (*User, error)
	DeletedByID(context.Context, *UserRequest) (*User, error)
	FindByID(context.Context, *UserRequest) (*User, error)
	GetUserMsg(context.Context, *MessageRequest) (*MessageResponse, error)
	FindMsgByID(context.Context, *MessageRequest) (*Message, error)
	CreateMessage(context.Context, *MessageRequest) (*empty.Empty, error)
	UpdateMsgByID(context.Context, *MessageRequest) (*Message, error)
	DeletedMsgByID(context.Context, *MessageRequest) (*Message, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) ListUsers(ctx context.Context, req *Request) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUsers not implemented")
}
func (*UnimplementedUserServiceServer) CreateUser(ctx context.Context, req *User) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (*UnimplementedUserServiceServer) UpdatedByID(ctx context.Context, req *UserRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatedByID not implemented")
}
func (*UnimplementedUserServiceServer) DeletedByID(ctx context.Context, req *UserRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletedByID not implemented")
}
func (*UnimplementedUserServiceServer) FindByID(ctx context.Context, req *UserRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindByID not implemented")
}
func (*UnimplementedUserServiceServer) GetUserMsg(ctx context.Context, req *MessageRequest) (*MessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserMsg not implemented")
}
func (*UnimplementedUserServiceServer) FindMsgByID(ctx context.Context, req *MessageRequest) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindMsgByID not implemented")
}
func (*UnimplementedUserServiceServer) CreateMessage(ctx context.Context, req *MessageRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMessage not implemented")
}
func (*UnimplementedUserServiceServer) UpdateMsgByID(ctx context.Context, req *MessageRequest) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMsgByID not implemented")
}
func (*UnimplementedUserServiceServer) DeletedMsgByID(ctx context.Context, req *MessageRequest) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletedMsgByID not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpctask.UserService/ListUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ListUsers(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpctask.UserService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdatedByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdatedByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpctask.UserService/UpdatedByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdatedByID(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DeletedByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DeletedByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpctask.UserService/DeletedByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DeletedByID(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_FindByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).FindByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpctask.UserService/FindByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).FindByID(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUserMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUserMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpctask.UserService/GetUserMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUserMsg(ctx, req.(*MessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_FindMsgByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).FindMsgByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpctask.UserService/FindMsgByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).FindMsgByID(ctx, req.(*MessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_CreateMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpctask.UserService/CreateMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateMessage(ctx, req.(*MessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateMsgByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateMsgByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpctask.UserService/UpdateMsgByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateMsgByID(ctx, req.(*MessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DeletedMsgByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DeletedMsgByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpctask.UserService/DeletedMsgByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DeletedMsgByID(ctx, req.(*MessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpctask.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListUsers",
			Handler:    _UserService_ListUsers_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _UserService_CreateUser_Handler,
		},
		{
			MethodName: "UpdatedByID",
			Handler:    _UserService_UpdatedByID_Handler,
		},
		{
			MethodName: "DeletedByID",
			Handler:    _UserService_DeletedByID_Handler,
		},
		{
			MethodName: "FindByID",
			Handler:    _UserService_FindByID_Handler,
		},
		{
			MethodName: "GetUserMsg",
			Handler:    _UserService_GetUserMsg_Handler,
		},
		{
			MethodName: "FindMsgByID",
			Handler:    _UserService_FindMsgByID_Handler,
		},
		{
			MethodName: "CreateMessage",
			Handler:    _UserService_CreateMessage_Handler,
		},
		{
			MethodName: "UpdateMsgByID",
			Handler:    _UserService_UpdateMsgByID_Handler,
		},
		{
			MethodName: "DeletedMsgByID",
			Handler:    _UserService_DeletedMsgByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/grpctask.proto",
}
